### ISSUE TITLE
Feature Request: As a member of the Shares Service team, I need to know how to automate the deployment of in-cluster shared services using Flux, so that I don’t have to it manually

### ISSUE THREAD

**Issue by bahramr** [Azure/aks-baseline-automation#30]
Description:
Add the code and document the steps to deploy the shared-services using GitOps with Flux. The Shared Services team is responsible for maintaining the overall health of the AKS clusters and the common components that run on them, such as monitoring, networking, security and other utility services. We need to provide sample code and guidance for how to bootstrap these services as part of the initial AKS deployment and also how to automate their on-going life-cycle management. These shared services, may be AKS add-ons such as [AAD Pod identity](https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity) or [Secret Store CSI Driver Provider](https://github.com/Azure/secrets-store-csi-driver-provider-azure), 3rd party such as [Prisma defender](https://docs.paloaltonetworks.com/prisma/prisma-cloud) or [Splunk](https://github.com/splunk/splunk-connect-for-kubernetes) daemonsets, or open source such as [Traefik](https://doc.traefik.io/traefik/v1.7/user-guide/kubernetes/), [KEDA](https://keda.sh/), [External-dns](https://github.com/kubernetes-sigs/external-dns#:~:text=ExternalDNS%20supports%20multiple%20DNS%20providers%20which%20have%20been%2cand%20we%20have%20limited%20resources%20to%20test%20changes.) or [Cert-manager](https://cert-manager.io/docs/). 

Acceptance Criteria:

1. Complete code for flux can be found in the shared-services folder of the repo [aks-baseline-automation/shared-services](https://github.com/Azure/aks-baseline-automation). At a minimum deploy the ingress controller Traefik through Flux, meaning automating these steps: https://github.com/mspnp/aks-baseline/blob/main/09-secret-management-and-ingress-controller.md.
2. Readme file has been created detailing how to use this deployment pattern [aks-baseline-automation/shared-services](https://github.com/Azure/aks-baseline-automation/tree/main/shared-services)

**Comment by carmodyquinnms** [comment]
Tried multiple solutions and decided to go with a workflow for deployment.  Initial checkin of solution is branch carmodyquinn-traefik

**Comment by carmodyquinnms** [comment]
This is closed out
