### ISSUE TITLE
Add helm chart of the Azure-Vote sample to this repo

### ISSUE THREAD

**Issue by Gordonby** [Azure/aks-baseline-automation#36]
Currently this repo contains a compiled version of the AzureVote helm chart.
The helm chart source is currently maintained [here](https://github.com/Gordonby/minihelm)
We should bring the helm chart into this repo.

**Comment by bahramr** [comment]
The helm charts have now been added to the repo here: https://github.com/Azure/aks-baseline-automation/blob/main/workloads/azure-vote/AzureVote.tgz
